framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # Redis
        app: cache.adapter.array
        system: cache.adapter.array
        #default_redis_provider: redis://localhost