doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    #charset: UTF-8
    options:
      !php/const \PDO::ATTR_PERSISTENT: true
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App

      Core:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Core/Entity'
        prefix: 'App\Core\Entity'
        alias: Core

#PROD
when@prod:
  framework:
    cache:
      pools:
        doctrine.system_cache_pool:
          adapter: cache.system
        doctrine.result_cache_pool:
          adapter: cache.app

  doctrine:
    orm:
      auto_generate_proxy_classes: false
      metadata_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

#TEST
when@test:
  doctrine:
    dbal:
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'
