doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: UTF-8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Core:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'App\Core\Entity'
                alias: Core

#PROD
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            #result_cache_driver: cache.app
            #query_cache_driver: cache.system
            #metadata_cache_driver: cache.system

#TEST
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
