framework:
    notifier:
        chatter_transports:
            firebase: '%env(FIREBASE_DSN)%'
            # firebase: 'null://null'
        texter_transports:
            main: 'null://null'
            tr: 'null://null'
