framework:
    notifier:
        chatter_transports:
            firebase: '%env(FIREBASE_DSN)%'
        texter_transports:
            main: '%env(SMS_MAIN_TRANSPORT)%'
            tr: '%env(SMS_TR_TRANSPORT)%'
