framework:
    notifier:
        #chatter_transports:
        #    slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
            firebase: '%env(FIREBASE_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        admin_recipients:
            - { email: admin@example.com }
