security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user_provider:
            entity:
                class: App\Core\Entity\User
    firewalls:
        # Profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # API Firewall
        main:
            security: true
            pattern: ^/api
            provider: user_provider
            lazy: true
            stateless: true
            custom_authenticator: App\Core\Security\JwtAuthenticator
            user_checker: App\Core\Security\UserChecker
            switch_user: { role: SWITCH_USER }
            json_login:
                check_path: api_login

    access_control:
        # Auth
        - { path: ^/api/v1/(login|refresh-token|logout|register|resetting|reset-password), roles: PUBLIC_ACCESS }

        # Global
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
