storage:
  default: "%env(APP_STORAGE)%"
  devices:
    local:
      driver: local
      root: "%kernel.project_dir%/storage/files/"

#    main:
#      driver: cloudflare
#      root: /
#      accessKey: ""
#      secretKey: ""
#      bucket: "bucket-id"
#      region: "auto"
#      endPoint: "https://*.r2.cloudflarestorage.com"
