swoole:
  entrypoint: bin/index.php
  watch_dir: "/config,/src,/templates"
  watch_extension: "*.php,*.yaml,*.yml,*.twig"
  replace_http_client: true # Replace Symfony HTTP Client to Swoole Client
  cron_worker: true
  task_worker: true
  failed_task_retry: "@EveryMinute10"
  failed_task_attempt: 2
