framework:
    # Default Locale
    default_locale: en

    # Enabled Locales
    enabled_locales: [ 'en', 'tr' ]

    # Request Language to Accept Language
    set_locale_from_accept_language: true

    translator:
        fallbacks: ['en']
        paths:
            - '%kernel.project_dir%/src/Admin/Core/Translation'
            - '%kernel.project_dir%/src/Admin/Pusher/Translation'