services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Commands
    Package\SwooleBundle\Command\:
        resource: '../../Command/*'

    # Custom Logger
    logger:
        class: Package\SwooleBundle\Log\Logger
        arguments:
            $output: "%kernel.logs_dir%/%env(APP_ENV)%.log"
            $minLevel: "%env(LOG_LEVEL)%"
            $stdin: "%env(LOG_STDIN)%"

    # Task Worker
    Package\SwooleBundle\Task\TaskHandler:

    # Cron Worker
    Package\SwooleBundle\Cron\CronHandler:
