services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Package\SwooleBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests,Runtime,Log,Task,Cron}'

    logger:
        class: Package\SwooleBundle\Log\Logger
        arguments:
            $output: "%kernel.logs_dir%/%env(APP_ENV)%.log"
            $minLevel: "%env(LOG_LEVEL)%"
            $stdin: "%env(LOG_STDIN)%"