services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Package\SwooleBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests,Runtime,Public,Server}'
