parameters:
    core.refresh_token_exp: "%env(APP_JWT_REFRESH_TOKEN_EXP)%"

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Services All Modules
    App\Admin\:
        resource: './'
        exclude:
            - './*/DependencyInjection'
            - './*/Entity'
            - './*/Enum'
            #- './*/Event'
            - './*/Exception'
            - './*/Request'
            - './*/Translation'

    # JWT Token Manager
    Ahc\Jwt\JWT:
        arguments:
            $key: "%env(APP_JWT_SECRET)%"
            $algo: 'HS256'
            $maxAge: "%env(APP_JWT_TOKEN_EXP)%"
        public: true

    # Logging
    logger:
        class: Symfony\Component\HttpKernel\Log\Logger
        arguments: ['info', '%kernel.logs_dir%/%kernel.environment%.log', null, '@request_stack']