parameters:
    core.refresh_token_exp: "%env(APP_JWT_REFRESH_TOKEN_EXP)%"
    core.log.file: "%kernel.logs_dir%/%kernel.environment%.log"

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Services All Modules
    App\Admin\:
        resource: './'
        exclude:
            - './*/Dto'
            - './*/DependencyInjection'
            - './*/Entity'
            - './*/Enum'
            - './*/Event'
            - './*/Exception'
            - './*/Permission'
            - './*/Factory'

    # JWT Token Manager
    Ahc\Jwt\JWT:
        arguments:
            $key: "%env(APP_JWT_SECRET)%"
            $algo: 'HS256'
            $maxAge: "%env(APP_JWT_TOKEN_EXP)%"
        public: true

    # Logging
    logger:
        class: Symfony\Component\HttpKernel\Log\Logger
        arguments: ["%env(APP_LOG_LEVEL)%", "%env(default:core.log.file:APP_LOG_FILE)%", null, '@request_stack', "%kernel.debug%"]
