name: App Deploy Staging
on:
  push:
    branches: [ staging ]

env:
  registry: ghcr.io
  app_image: ghcr.io/${{ github.repository }}:staging
  ssh_username: root
  ssh_privatekey: ${{ secrets.SERVER_PRIVATEKEY }}
  ssh_hosts: ${{ vars.STAG_HOSTS }}
  app_envs: ${{ join(fromJSON(vars.STAG_ENVS), '\n') }}

jobs:
  build:
    # Configuration
    name: Image Build & Push GHCR
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    # Steps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.app_image }}
          labels: |
            org.opencontainers.image.title=StagingImage
            org.opencontainers.image.source="${{ github.event.repository.html_url }}"

  deploy:
    # Configuration
    needs: build
    name: Deploy to Servers
    runs-on: ubuntu-22.04
    permissions:
      packages: read

    # Steps
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.ssh_hosts }}
          username: ${{ env.ssh_username }}
          key: ${{ env.ssh_privatekey }}
          script: |
            echo -e "${{ env.app_envs }}" > .env
            echo "DATABASE_URL=postgres://postgres:postgres2315@postgres:5432/postgres?charset=utf8&serverVersion=14" >> .env
            echo "LOCK_DSN=postgresql+advisory://postgres:postgres2315@postgres:5432/postgres?serverVersion=14" >> .env
            echo ${{ secrets.ACCESS_TOKEN }} | docker login ${{ env.registry }} -u ${{ github.actor }} --password-stdin
            docker stop -t 120 mainapp || true && docker rm mainapp || true
            docker pull ${{ env.app_image }}
            docker run --name postgres -e POSTGRES_PASSWORD=postgres2315 -v /pgdata:/var/lib/postgresql/data -p 5432:5432 -d postgres:14-alpine || true
            docker run --link=postgres:postgres --env-file .env --rm ${{ env.app_image }} sh -c "bin/console doctrine:schema:update --force --complete" || true
            docker run --link=postgres:postgres --env-file .env -d -p 80:80 --name mainapp --restart always --log-opt max-size=1g ${{ env.app_image }}
            docker rmi $(docker images -q -f 'dangling=true') || true