name: App Deploy Staging
on:
  push:
    branches: [ staging ]

env:
  registry: ghcr.io
  app_image: ghcr.io/${{ github.repository }}:staging
  ssh_username: root
  ssh_privatekey: ${{ secrets.SERVER_PRIVATEKEY }}
  ssh_hosts: ${{ vars.STAG_HOSTS }}
  app_envs: ${{ join(fromJSON(vars.STAG_ENVS), '\n') }}

jobs:
  build:
    # Configuration
    name: Image Build & Push GHCR
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    # Steps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.app_image }}
          labels: |
            org.opencontainers.image.title=StagingImage
            org.opencontainers.image.source="${{ github.event.repository.html_url }}"

  deploy:
    # Configuration
    needs: build
    name: Deploy to Servers
    runs-on: ubuntu-22.04
    permissions:
      packages: read
      contents: 'read'

    # Steps
    steps:
      - name: Read Compose File
        id: compose
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: .github/docker/staging-compose.yml
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.ssh_hosts }}
          username: ${{ env.ssh_username }}
          key: ${{ env.ssh_privatekey }}
          script: |
            APPIMAGE=${{ env.app_image }}
            tee docker-compose.yml <<EOF
            ${{ steps.compose.outputs.content }}
            EOF
            echo -e "${{ env.app_envs }}" > .env
            
            echo "DATABASE_URL=postgres://postgres:postgres2315@postgres:5432/postgres?charset=utf8&serverVersion=14" >> .env
            echo "LOCK_DSN=postgresql+advisory://postgres:postgres2315@postgres:5432/postgres?serverVersion=14" >> .env
            
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.registry }} -u ${{ github.actor }} --password-stdin
            docker pull ${{ env.app_image }}
            docker compose stop
            docker compose up -d --remove-orphans
            docker rmi $(docker images -q -f 'dangling=true') || true
